In [2]:
import numpy as np
A=np.arange(3*4)
B=np.arange(4*3)
A=A.reshape(3,4) #3x4
B=B.reshape(4,3) #4x3
print("A=\n",A)
print("B=\n",B)

A=
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
B=
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


求$C_{ij}=\sum_{k}^4A_{ik}B_{kj}$

In [3]:
def C_ij(A,B,i,j):
    c=0
    for k in range(4):
        c+=A[i,k]*B[k,j]
    return c
C=np.zeros((3,3))
for i in range(3):
    for j in range(3):
        C[i,j]=C_ij(A,B,i,j)
print("C=\n",C) 

C=
 [[ 42.  48.  54.]
 [114. 136. 158.]
 [186. 224. 262.]]


In [4]:
C=np.dot(A,B)
print("C=\n",C)

C=
 [[ 42  48  54]
 [114 136 158]
 [186 224 262]]


求$C_{ij}=A_{ik}B_{kj}$

In [5]:
C=np.einsum('ik,kj->ij',A,B)
print("C=",C)

C= [[ 42  48  54]
 [114 136 158]
 [186 224 262]]


求$C_{ij}=A_{ik}B_{kj}$

In [20]:
C=np.tensordot(A,B,axes=[(1,),(0,)])# ik kj
print("C=",C)

C= [[ 42  48  54]
 [114 136 158]
 [186 224 262]]


求$C_{ij}=\sum_{k}^3A_{ki}B_{jk}$

In [24]:
def C_ij(A,B,i,j):
    c=0
    for k in range(3):
        c+=A[k,i]*B[j,k]
    return c
C=np.zeros((4,4))
for i in range(4):
    for j in range(4):
        C[i,j]=C_ij(A,B,i,j)
print("C=\n",C) 

C=
 [[ 20.  56.  92. 128.]
 [ 23.  68. 113. 158.]
 [ 26.  80. 134. 188.]
 [ 29.  92. 155. 218.]]


In [23]:
C=np.dot(B,A)
print("C=\n",C)

C=
 [[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]]


In [25]:
C=np.einsum('ki,jk->ij',A,B)
print("C=",C)

C= [[ 20  56  92 128]
 [ 23  68 113 158]
 [ 26  80 134 188]
 [ 29  92 155 218]]


In [26]:
C=np.tensordot(A,B,axes=[(0,),(1,)])# ki jk
print("C=",C)

C= [[ 20  56  92 128]
 [ 23  68 113 158]
 [ 26  80 134 188]
 [ 29  92 155 218]]


In [1]:
import numpy as np
A=np.arange(4*4*3)
B=np.arange(3*3*2)
A=A.reshape(4,4,3) #4x4x3
B=B.reshape(3,3,2) #3x3x2
print("A=\n",A)
print("B=\n",B)

A=
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]

 [[36 37 38]
  [39 40 41]
  [42 43 44]
  [45 46 47]]]
B=
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]]


求$C_{jxn}=\sum_{i}^4\sum_{k}^3\sum_{m}^3A_{ijk}B_{kmn}A_{ixm}$

In [2]:
def C_jxn(A,B,j,x,n):
    c=0
    for i in range(4):
        for k in range(3):
            for m in range(3):
                c+=A[i,j,k]*B[k,m,n]*A[i,x,m]
    return c
C=np.zeros((4,4,2))
for j in range(4):
    for x in range(4):
        for n in range(2):
            C[j,x,n]=C_jxn(A,B,j,x,n)
print("C=",C)   

C= [[[159456. 178932.]
  [176304. 197832.]
  [193152. 216732.]
  [210000. 235632.]]

 [[176016. 197544.]
  [195456. 219360.]
  [214896. 241176.]
  [234336. 262992.]]

 [[192576. 216156.]
  [214608. 240888.]
  [236640. 265620.]
  [258672. 290352.]]

 [[209136. 234768.]
  [233760. 262416.]
  [258384. 290064.]
  [283008. 317712.]]]


求$C_{jxn}=A_{ijk}B_{kmn}A_{ixm}$

In [3]:
C=np.einsum('ijk,kmn,ixm->jxn',A,B,A)
print("C=",C) 
print(C.shape)

C= [[[159456 178932]
  [176304 197832]
  [193152 216732]
  [210000 235632]]

 [[176016 197544]
  [195456 219360]
  [214896 241176]
  [234336 262992]]

 [[192576 216156]
  [214608 240888]
  [236640 265620]
  [258672 290352]]

 [[209136 234768]
  [233760 262416]
  [258384 290064]
  [283008 317712]]]
(4, 4, 2)


In [4]:
Z=np.tensordot(A,B,axes=[(2,),(0,)])
# ijmn ixm
X=np.tensordot(Z,A,axes=[(0,2),(0,2)])
# jnx
#C=np.transpose(X,axes=[0,2,1])
print("C=",C)
print(C.shape)

C= [[[159456 178932]
  [176304 197832]
  [193152 216732]
  [210000 235632]]

 [[176016 197544]
  [195456 219360]
  [214896 241176]
  [234336 262992]]

 [[192576 216156]
  [214608 240888]
  [236640 265620]
  [258672 290352]]

 [[209136 234768]
  [233760 262416]
  [258384 290064]
  [283008 317712]]]
(4, 4, 2)


In [28]:
import numpy as np
A=np.array([["a11","a12"],["a21","a22"],["a31","a32"]])
X=np.array([["x11","x12"],["x21","x22"]])
F=np.array([["a11x11+a12x21","a11x12+a12x22"],["a21x11+a22x21","a21x12+a22x22"],["a31x11+a32x21","a31x12+a32x22"]])
print("A=\n",A)
print("X=\n",X)
print("F=\n",F)
for i in range(3):
    for j in range(2):
        for k in range(2):
            for s in range(2):
                if j==s:
                    print("M[%d,%d,%d,%d]=F%d%d/x%d%d=(%s)/%s=%s"%(i+1,j+1,k+1,s+1,i+1,j+1,k+1,s+1,F[i,j],X[k,s],"a%d%d"%(i+1,k+1)))
                else:
                    print("M[%d,%d,%d,%d]=F%d%d/x%d%d=(%s)/%s=0"%(i+1,j+1,k+1,s+1,i+1,j+1,k+1,s+1,F[i,j],X[k,s]))

A=
 [['a11' 'a12']
 ['a21' 'a22']
 ['a31' 'a32']]
X=
 [['x11' 'x12']
 ['x21' 'x22']]
F=
 [['a11x11+a12x21' 'a11x12+a12x22']
 ['a21x11+a22x21' 'a21x12+a22x22']
 ['a31x11+a32x21' 'a31x12+a32x22']]
M[1,1,1,1]=F11/x11=(a11x11+a12x21)/x11=a11
M[1,1,1,2]=F11/x12=(a11x11+a12x21)/x12=0
M[1,1,2,1]=F11/x21=(a11x11+a12x21)/x21=a12
M[1,1,2,2]=F11/x22=(a11x11+a12x21)/x22=0
M[1,2,1,1]=F12/x11=(a11x12+a12x22)/x11=0
M[1,2,1,2]=F12/x12=(a11x12+a12x22)/x12=a11
M[1,2,2,1]=F12/x21=(a11x12+a12x22)/x21=0
M[1,2,2,2]=F12/x22=(a11x12+a12x22)/x22=a12
M[2,1,1,1]=F21/x11=(a21x11+a22x21)/x11=a21
M[2,1,1,2]=F21/x12=(a21x11+a22x21)/x12=0
M[2,1,2,1]=F21/x21=(a21x11+a22x21)/x21=a22
M[2,1,2,2]=F21/x22=(a21x11+a22x21)/x22=0
M[2,2,1,1]=F22/x11=(a21x12+a22x22)/x11=0
M[2,2,1,2]=F22/x12=(a21x12+a22x22)/x12=a21
M[2,2,2,1]=F22/x21=(a21x12+a22x22)/x21=0
M[2,2,2,2]=F22/x22=(a21x12+a22x22)/x22=a22
M[3,1,1,1]=F31/x11=(a31x11+a32x21)/x11=a31
M[3,1,1,2]=F31/x12=(a31x11+a32x21)/x12=0
M[3,1,2,1]=F31/x21=(a31x11+a32x21)/x21=a32
M[3,1,